###register request
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "arash",
    "email":"arash@gmail.com",
    "mobile":"09050565501",
    "password":"123456",
    "confirm_password":"123456"
}
###login register request
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: bearer {{$dotenv TOKEN}}

{
    "username":"mohammad",
    "password": "123456"     
}