###register request
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "mohammad",
    "email":"mohammad@gmail.com",
    "mobile":"09050204501",
    "password":"123456",
    "confirm_password":"123456"
}
###login register request
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: bearer {{$dotenv TOKEN}}

{
    "username":"kiarash",
    "password": "123456"     
}